##############################################################################################################################

proxy-groups:
-
  name: Proxy
  type: select
  include-all-proxies: true
  proxies:
  - Auto
  - Cross ⚖️
  - DIRECT
  udp: true
  use:
  - sakura
  
-
  name: Auto
  type: url-test
  include-all-proxies: true
  filter: "日本|韩|台湾|香港|新加坡|jp|kr|tw|hk|sg"
  exclude-filter: "通用|标准|解锁|自动|回落|官网|直连|专线"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3600
  hidden: true
  udp: true
  use:
  - sakura
-
  name: "Cross ⚖️"
  type: select
  proxies:
  - Domestic
  - HK 🇭🇰
  - TW 🇹🇼
  - JP 🇯🇵
  - KR 🇰🇷
  - SG 🇸🇬
  - US 🇺🇸
  - EU 🇪🇺
  - RU 🇷🇺
  - ME 🇸🇦
  - OC 🇭🇲
   
-
  name: "Social 💬"
  type: select
  proxies:
  - Proxy
  - JP 🇯🇵
  - KR 🇰🇷
  - HK 🇭🇰
  - TW 🇹🇼
  - US 🇺🇸
  - Domestic

-
  name: "Service 📶"
  type: select
  proxies:
  - Proxy
  - US 🇺🇸
  - JP 🇯🇵
  - KR 🇰🇷
  - Domestic

-
  name: "AI 🤖"
  type: select
  proxies:
  - Proxy
  - US 🇺🇸
  - Domestic

-
  name: "Media 📺"
  type: select
  proxies:
  - Proxy
  - US 🇺🇸
  - JP 🇯🇵
  - KR 🇰🇷
  - HK 🇭🇰
  - TW 🇹🇼
  - Domestic
  include-all-proxies: true
  filter: "(?i)视频|油管|网飞|media"

-  
  name: "Others 🛰️"
  type: select
  proxies:
  - Proxy
  - Domestic
  udp: true

-
  name: "Wall 🧱"
  type: select
  proxies:
  - Proxy
  - Domestic

-
  name: "HK 🇭🇰"
  type: select
  proxies:
  - HK
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)香港|hk"
  use:
  - sakura
  - kle
   
-
  name: "TW 🇹🇼"
  type: select
  proxies:
  - TW
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)台湾|tw"
  use:
  - sakura
  - kle

-
  name: "JP 🇯🇵"
  type: select
  proxies:
  - JP
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)日本|jp"
  use:
  - sakura
  - kle
   
-
  name: "KR 🇰🇷"
  type: select
  proxies:
  - KR
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)韩|kr"
  use:
  - sakura
  - kle

-
  name: "SG 🇸🇬"
  type: select
  proxies:
  - SG
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)新加坡|狮城|sg"
  use:
  - sakura
  - kle

-
  name: "OC 🇭🇲"
  type: select
  proxies:
  - OC
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)澳大|斐济|新西兰|南极"
  use:
  - sakura
  - kle

-
  name: "EU 🇪🇺"
  type: select
  proxies:
  - EU
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)德国|法国|英国|意大利"
  use:
  - sakura
  - kle

-
  name: "US 🇺🇸"
  type: select
  proxies:
  - US
  - LA
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)美国|us"
  use:
  - sakura
  - kle
   
-
  name: "RU 🇷🇺"
  type: select
  proxies:
  - RU
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)俄|乌克|ru"
  use:
  - sakura
  - kle
   
-
  name: "ME 🇸🇦"
  type: select
  proxies:
  - SA
  - IS
  - TR
  - IB
  - Domestic
  - REJECT
  include-all-proxies: true
  filter: "(?i)迪拜|土耳其|sa|tr|ib"
  use:
  - sakura
  - kle


-
  name: "Game 🎮"
  type: select
  proxies:
  - Domestic
  - Proxy
  - US 🇺🇸
  - JP 🇯🇵
  - KR 🇰🇷
  - ME 🇸🇦
  - REJECT
  include-all-proxies: true
  filter: "(?i)游戏|game"
  udp : true  

-
  name: "BlackHole 🧅"
  type: select
  proxies:
  - REJECT
  - REJECT-DROP
  - Domestic
  - Proxy

-
  name: "Domestic 🏠"
  type: select
  proxies:
  - DIRECT

-
  name: US
  type: url-test
  include-all-proxies: true
  filter: "(?i)美国|us"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3000
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: RU
  type: url-test
  include-all-proxies: true
  filter: "(?i)俄|乌克|ru"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3200
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: IB
  type: url-test
  include-all-proxies: true
  filter: "(?i)印度|巴基斯坦|ib"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3200
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: SA
  type: url-test
  include-all-proxies: true
  filter: "(?i)迪拜|阿联|sa"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3400
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: TR
  type: url-test
  include-all-proxies: true
  filter: "(?i)土耳其|斯坦|tr"
  exclude-filter: "通用|标准|解锁|自动|巴基斯坦"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3200
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: JP
  type: url-test
  include-all-proxies: true
  filter: "(?i)日本|jp"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3600
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: KR
  type: url-test
  include-all-proxies: true
  filter: "(?i)韩|kr"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 3800
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: SG
  type: url-test
  include-all-proxies: true
  filter: "(?i)新加坡|sg"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 4000
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: HK
  type: url-test
  include-all-proxies: true
  filter: "(?i)香港|hk"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 4200
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: TW
  type: url-test
  include-all-proxies: true
  filter: "(?i)台湾|tw"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 4400
  lazy: true
  hidden: true
  use:
  - sakura
  - kle

-
  name: EU
  type: url-test
  include-all-proxies: true
  filter: "(?i)德国|法国|英国|意大利|西班牙"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 4600
  lazy: true
  hidden: true
  use:
  - sakura
  - kle

-
  name: OC
  type: url-test
  include-all-proxies: true
  filter: "(?i)澳大利亚|斐济|新西兰|南极"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 4800
  lazy: true
  hidden: true
  use:
  - sakura
  - kle

-
  name: LA
  type: url-test
  include-all-proxies: true
  filter: "(?i)秘鲁|玻利维亚|阿根廷|巴西"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 5000
  lazy: true
  hidden: true
  use:
  - sakura
  - kle

-
  name: IS
  type: url-test
  include-all-proxies: true
  filter: "(?i)埃及|也门|伊拉克|以色列|约旦"
  exclude-filter: "通用|标准|解锁|自动"
  url: 'https://www.gstatic.com/generate_204'
  interval: 5200
  lazy: true
  hidden: true
  use:
  - sakura
  - kle
   
-
  name: Domestic
  type: select
  proxies:
  - Domestic 🏠
  hidden: true

##############################################################################################################################

##############################################################################################################################

# 规则
rules:
  - PROCESS-NAME,tailscaled,DIRECT
  - IP-SUFFIX,154.16.183.43/24,REJECT-DROP
  - DOMAIN-SUFFIX,xns.one,Proxy
  - DOMAIN-SUFFIX,nxns.link,Proxy
  - DOMAIN-SUFFIX,bing.com,DIRECT
  - DOMAIN,ptest-1.ipcheck.ing,RU 🇷🇺
  - DOMAIN,ptest-2.ipcheck.ing,ME 🇸🇦
  - DOMAIN,ptest-3.ipcheck.ing,OC 🇭🇲
  - DOMAIN,ptest-4.ipcheck.ing,EU 🇪🇺
  - DOMAIN,ptest-5.ipcheck.ing,US 🇺🇸
  - DOMAIN,ptest-6.ipcheck.ing,SG 🇸🇬
  - DOMAIN,ptest-7.ipcheck.ing,KR 🇰🇷
  - DOMAIN,ptest-8.ipcheck.ing,JP 🇯🇵

  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
#  - RULE-SET,reject,REJECT
  - RULE-SET,bilibili,Cross ⚖️
  - RULE-SET,paypal,Cross ⚖️
  - RULE-SET,ai,AI 🤖
  - RULE-SET,bahamut,Social 💬
  - RULE-SET,youtube,Media 📺
  - RULE-SET,spotify,Media 📺
  - RULE-SET,disney,Media 📺
  - RULE-SET,google,Service 📶
  - RULE-SET,icloud,Service 📶
  - RULE-SET,apple,Service 📶
  - RULE-SET,gfw,Wall 🧱
  - RULE-SET,proxy,Proxy
#  - AND,((DOMAIN,steamserver.net),(NETWORK,UDP)),Game 🎮
#  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,Social 💬,no-resolve
  - RULE-SET,twitter-cidr,Social 💬,no-resolve
  - RULE-SET,netflix-cidr,Media 📺,no-resolve
  - RULE-SET,cloudflare-cidr,Service 📶,no-resolve
#  - RULE-SET,us-cidr,US 🇺🇸,no-resolve
  - RULE-SET,jp-cidr,JP 🇯🇵,no-resolve
  - RULE-SET,kr-cidr,KR 🇰🇷,no-resolve
  - RULE-SET,tor-cidr,BlackHole 🧅,no-resolve
  
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,Others 🛰️
  - DST-PORT,443,Others 🛰️
  - NETWORK,udp,DIRECT
  - MATCH,Proxy

  
# 规则集
rule-providers:
#  reject:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
#    path: ./rule_provider/reject.yaml
#    interval: 172800

  bilibili:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/bilibili.txt"
    path: ./rule_provider/bilibili.yaml
    interval: 86400
  
  paypal:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/paypal.txt"
    path: ./rule_provider/paypal.yaml
    interval: 86400

  bahamut:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/bahamut.txt"
    path: ./rule_provider/bahamut.yaml
    interval: 86400

  ai:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/ai.txt"
    path: ./rule_provider/ai.yaml
    interval: 86400

  disney:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/disney.txt"
    path: ./rule_provider/disney.yaml
    interval: 86400

  youtube:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/youtube.txt"
    path: ./rule_provider/youtube.yaml
    interval: 86400

  spotify:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/inoribea/DivineEngine-Inheritance@main/list/spotify.txt"
    path: ./rule_provider/spotify.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./rule_provider/icloud.yaml
    interval: 176400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./rule_provider/apple.yaml
    interval: 176400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./rule_provider/google.yaml
    interval: 180000

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 259200

#  direct:
#    type: http
#    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
#    path: ./rule_provider/direct.yaml
#    interval: 252000

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./rule_provider/private.yaml
    interval: 172800

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./rule_provider/gfw.yaml
    interval: 173800

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 174800

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 175800

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./rule_provider/telegramcidr.yaml
    interval: 172800

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./rule_provider/applications.yaml
    interval: 172800
  
#  us-cidr:
#    type: http
#    behavior: ipcidr
#    format: mrs
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/us.mrs"
#    path: ./mrs/geoip/us.mrs
#    interval: 432000
    
  jp-cidr:
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/jp.mrs"
    path: ./mrs/geoip/jp.mrs
    interval: 345600

  kr-cidr:
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/kr.mrs"
    path: ./mrs/geoip/kr.mrs
    interval: 347600
      
  twitter-cidr: 
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/twitter.mrs"
    path: ./mrs/geoip/twitter.mrs
    interval: 170800

  netflix-cidr: 
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/netflix.mrs"
    path: ./mrs/geoip/netflix.mrs
    interval: 172800


  cloudflare-cidr: 
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/cloudflare.mrs"
    path: ./mrs/geoip/cloudflare.mrs
    interval: 177800

  tor-cidr: 
    type: http
    behavior: ipcidr
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/mrs/tor.mrs"
    path: ./mrs/geoip/tor.mrs
    interval: 182000

##############################################################################################################################
